language: python
python:
  - 2.7
# Can't test Python 3 until ml_metrics gets updated
#  - 3.2
#  - 3.3

notifications:
  email: false

# Install stuff
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-scipy python-nose
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install python-coveralls --use-mirrors
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - python setup.py install

# Run test
script:
  - nosetests --with-coverage --cover-package=skll tests/test_skll.py

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
