language: python
python:
  - "2.7"
# Can't test Python 3 until ml_metrics gets updated
#  - "3.2"
#  - "3.3"

notifications:
  email: false

# Install stuff
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-scipy python-nose python-numpy
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "python setup.py install"

# Run test
script: nosetests tests/test_skll.py
