language: python
python:
  - 2.7
  - 3.2

notifications:
  email: false

# Install stuff
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-scipy python-nose python3-scipy python3-nose
install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip install --use-mirrors configparser; fi
  - pip install -r requirements.txt --use-mirrors
  - pip install python-coveralls --use-mirrors
  - pip install nose-cov --use-mirrors
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - python setup.py install

# Run test
script:
  - nosetests --with-cov --cov skll --cov-config .coveragerc tests/test_skll.py

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
