language: python
python:
  - 2.7
  - 3.4
env:
  - GRIDMAP=true
  - GRIDMAP=false
  - GRIDMAP=true SKLL_MAX_CONCURRENT_PROCESSES=1
  - GRIDMAP=false SKLL_MAX_CONCURRENT_PROCESSES=1
notifications:
  email: false

# Install stuff
before_install:
  - if [ $GRIDMAP == "true" ]; then travis/install_sge.sh; fi
  - export SGE_ROOT=/var/lib/gridengine
  - export SGE_CELL=default
  - export DRMAA_LIBRARY_PATH=/usr/lib/libdrmaa.so.1.0
  - export GRID_MAP_REDIS_PORT=12345
  - sudo mkdir /scratch/
  - sudo chmod 777 /scratch/
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda config --add channels https://conda.binstar.org/dan_blanchard
  - conda update --yes conda
install:
  - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy beautiful-soup six scikit-learn joblib prettytable python-coveralls
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then conda install --yes configparser futures logutils; fi
  - if [ $GRIDMAP == "true" ]; then conda install --yes drmaa gridmap; fi
  # Have to use pip for nose-cov because its entry points are not supported by conda yet
  - pip install nose-cov
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - python setup.py install

# Run test
script:
  - nosetests --with-cov --cov skll --cov-config .coveragerc --logging-level=ERROR

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
  - tail -n 1000 /home/travis/build/EducationalTestingService/skll/tests/output/*.e*
  - tail -n 1000 /home/travis/build/EducationalTestingService/skll/tests/output/*.o*

# Print out scratch job info if failed
after_failure:
  - tail -n 1000 /home/travis/build/EducationalTestingService/skll/tests/output/*.e*
  - tail -n 1000 /home/travis/build/EducationalTestingService/skll/tests/output/*.o*
